
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - openzeppelin/openzeppelin-contracts@3.0.0
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
      - "@openzeppelin=openzeppelin/openzeppelin-contracts@3.0.0"
networks:
  defualt: development
  mainnet-fork:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
  development:
    eth_usd_price_feed: "0x0000000000000000000000000000000000000000"
